name: release

on:
  push: 
    tags:
      - '*'


jobs:
  buildTest:
    uses: AndresJR/p7decide/.github/workflows/django.yml@1
    with: 
      secrets: 
        CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}

  release:
    needs: buildTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2
      - name: Release
        uses: softprops/action-gh-release@1
