name: release

on:
  push: 
    tags:
      - '*'


jobs:
  buildTests:
      - uses: ./.github/workflows/django.yml

  release:
    needs: buildTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2
      - name: Release
        uses: softprops/action-gh-release@1
