name: release

on:
  push: 
    tags:
      - '*'
    branches:
      - master


jobs:
  buildTest:
    uses: AndresJR/p7decide/.github/workflows/django.yml@master

  release:
    needs: buildTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2
      - name: Release
        uses: softprops/action-gh-release@1
